### ISSUE TITLE
Terraform Provider Development Program

### ISSUE THREAD

**Issue by cgriggs01** [cherryservers/terraform-provider-cherryservers#1]
Hi Darius,

The provider looks good, this is a great start. I'll include my initial feedback below.

- [x] All `.go` files (except main.go) should reside under the directory `cherryservers/` in the root of your repository. In addition, the import path `"github.com/terraform-providers/terraform-provider-cherryservers/cherryservers"` to main.go, this will allow the provider to run its nightly acceptance test in our TeamCity environment. 

- [x] Resource files should include the name of the provider. So the file `resource_ip.go` will be `resource_cherryserver_ip.go`.

- [x] The provider and each resource file should have its own correspond acceptance test, with the same name plus the post-fix `_test.go`

- [x] Website documentation is stored in a `website/` directory. 
- Within the website directory, there must be an `cherryservers.erb` layout file (consul.erb) that is used to define the sidebar directory of the documentation. 
- Along with the layout file will be a `docs/` directory which is to store all of the Markdown documentation files
- Inside of the docs/ directory must be an `index.html.markdown` file, this is the provider main page and is used to document the high-level use of the integration and provider credentials references. 
- A `r/` directory is used to store all the resource_name.html.markdown documentation files. Each resource documentation page should have an example implementation and list out all of the attributes and arguments of the resource. 

- [x] The `provder.go` is lacking functions to configure a connector with the Cherry Servers platform. 

- [x] All Terraform providers have a GNUmakefile which is standard across all Terraform providers, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to `PKG_NAME=cherryservers`. This includes a change to use Go Modules for dependency management There are four bash scripts kept in a `scripts/` directory that are used in different processes of testing and release, these can all be copied from the [NULL provider](https://github.com/terraform-providers/terraform-provider-null/tree/master/scripts) 

- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a `.travis.yaml` file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “(Unreleased)” and will then be updated with a date by the tf-release-bot. 

- [x] To keep provider builds consistent, we require that all of the providers dependancies be checked into a `vendor/`directory within the repository. 

Looking forward to releasing this integration with you.
Best,
Chris

**Comment by ArturasRa** [comment]
Hi Chris,

it seems we managed to accomplish your initial notes on our terraform provider. Please review the changes and let us know if we need to do additional changes. Thanks.

**Comment by cgriggs01** [comment]
Hey Team, 

The provider is looking great, there are just a few more items to address before we can move forward to the release. 

- The `docs/` directory should be moved under the `website/` directory. For example, you can see the Github TF provider [website docs](https://github.com/terraform-providers/terraform-provider-github/tree/master/website). 

- Im not sure if we ever received a Cherry Servers Auth Token to run the acceptance test. Could you please provider these credentials through [this form](https://docs.google.com/forms/d/e/1FAIpQLSe5TjsThekgY0nUZan8M8JFVFk2qFC0shR6Fwpggn8XhhoHdg/viewform?usp=sf_link)

Let me know if you have any questions.

Best,
Chris

**Comment by cgriggs01** [comment]
Hey Team,

A few more items with the documentation.

Provider doc:
- [ ] Add attribute description with environment variable name for `auth_token`

IP Resource:
- [ ] The object `routed_to` is defined in the code as "optional" but listed as a "computed" attribute in the documentation. 
- [ ] the object `a_record` is not documented 
- [ ] The `ptr_record` attribute is listed in the docs as `ptr`   

Server Resource:
- [ ] Argument `user_data` and `tags` is not documented

SSH Resource:
- [ ] The attribute section should be formatted with its own section. The other resource docs follow the correct formatting. 

Looking forward to this release. Let me know if you have any questions.

**Comment by ArturasRa** [comment]
Hi Chris,

I did the changes. As of `IP resource` and `routed_to` atribute, it's optional since IP address can be routed to `hostname` (or server\`s IP - those variables are self excluded) instead of server\`s ID (since it's easier to remember), but the value of `routed_to` will be calculated in any case and will point to that server`s ID.
