### ISSUE TITLE
Nėra grąžinama klaida

### ISSUE THREAD

**Issue by deivis163** [cherryservers/terraform-provider-cherryservers#11]
Nėra grąžinama klaida,

main.tf turinys:

resource "cherryservers_project" "projektas" {
  team_id = "${var.team_id}"
  name = "${var.project_name}"
}

resource "cherryservers_ssh" "mykey" {
  name   = "terraformkey"
  public_key = "ssh-rsa AAAAB3NzaC1...
}

resource "cherryservers_ip" "floating-ip-main" {
  project_id = "${cherryservers_project.projektas.id}"
  region = "${var.region}"
}

resource "cherryservers_server" "HA" {
  project_id = "${cherryservers_project.projektas.id}"
  region = "EU-East-1"
  hostname = "HAproxy"
  image = "${var.image}"
  plan_id = "${var.plan_id}"
  ssh_keys_ids = [
    "${cherryservers_ssh.mykey.id}"]
  ip_addresses_ids = [
    "${cherryservers_ip.floating-ip-main.id}"]
}

Paleidus terraform output'as:

cherryservers_server.HA: Still creating... (10s elapsed)
cherryservers_server.HA: Still creating... (20s elapsed)
cherryservers_server.HA: Still creating... (30s elapsed)
cherryservers_server.HA: Still creating... (40s elapsed)
cherryservers_server.HA: Still creating... (50s elapsed)
cherryservers_server.HA: Still creating... (1m0s elapsed)
cherryservers_server.HA: Still creating... (1m10s elapsed)
cherryservers_server.HA: Still creating... (1m20s elapsed)
cherryservers_server.HA: Still creating... (1m30s elapsed)
cherryservers_server.HA: Still creating... (1m40s elapsed)
cherryservers_server.HA: Still creating... (1m50s elapsed)
cherryservers_server.HA: Still creating... (2m0s elapsed)
cherryservers_server.HA: Still creating... (2m10s elapsed)
cherryservers_server.HA: Still creating... (2m20s elapsed)
cherryservers_server.HA: Still creating... (2m30s elapsed)
cherryservers_server.HA: Still creating... (2m40s elapsed)

 ir vis bando, nors iš api atsakymas buvo:
 - - [30/Jan/2024:08:17:40 +0000] "POST /v1/projects/171764/servers HTTP/1.1" 400 657 "-" "Go-http-client/2.0"

**Comment by deivis163** [comment]
variable "region" {
  default = "EU-East-1"
}
variable "image" {
  default = "Ubuntu 22.04 64bit"
}
variable "project_name" {
  default = "Haproxy"
}
variable "team_id" {
  default = "15674"
}
variable "plan_id" {
  default = "161"
}

**Comment by Andrius521** [comment]
Gal galėtum pasitikrinti savo terraform-provider-cherryservers buildą ar tikrai esi susikonfigūravęs jį iš master šakos, nes serverio objekto sukūrimas neturėjo net prasidėti, kadangi nebuvo paduotas privalomas **plan** parametras. (gali pasiimti sau tinkantį subuildint'ą binary failą iš pre-release - https://github.com/Andrius521/terraform-provider-cherryservers/releases/tag/untagged-711155f3835b77634e00).

Pagal tavo pateiktą main.tf matau, kad yra paduodamas **plan_id**, tokio argumento nebėra cherry terraform provider'yje, jis taip pat buvo pašalintas ir iš cherry API, vietoje jo naudojamas **plan**,  kuris tikisi plano **slug** reikšmės.

---------
variable "region" {
default = "EU-East-1"
}
Tokios regiono reikšmės EU-East-1 jau nebėra, ji pakeista į EU-Nord-1, vietoje regiono vardo rekomenduočiau naudoti regiono **slug** reikšmę (serverio sukūrimas veiks ir su regiono vardu, bet nesu tikras ar visi API endpoint'ai vis dar palaiko name.), taip pat ir terraform provider tikisi slug reikšmės.

Terraform objektų priimamus parametrus ir informacija apie juos aprašyta čia - https://github.com/Andrius521/terraform-provider-cherryservers/tree/master/docs/resources

**Comment by deivis163** [comment]
Pavyko pasileisti.

**Comment by Andrius521** [comment]
Gerai, tuomet užsarau šitą issue.
