### ISSUE TITLE
Reinstall server when updating user data?

### ISSUE THREAD

**Issue by littleblackcloud** [cherryservers/terraform-provider-cherryservers#27]
I saw that `cherryctl` supports reinstalling a server with updated cloud-init data https://github.com/cherryservers/cherryctl/pull/36.

Would it be possible to expose the same functionality to the terraform provider with an option like `user_data_reinstall_on_change = true`, so that updating the user data would **reinstall** the existing server instead of destroying it?

**Comment by littleblackcloud** [comment]
hi @zalmarge! I think you meant to close #26 and not this issue.

**Comment by caliban0** [comment]
Oops, wrong issue closed, reopening.

**Comment by zalmarge** [comment]
> I saw that `cherryctl` supports reinstalling a server with updated cloud-init data [cherryservers/cherryctl#36](https://github.com/cherryservers/cherryctl/pull/36).
> 
> Would it be possible to expose the same functionality to the terraform provider with an option like `user_data_reinstall_on_change = true`, so that updating the user data would **reinstall** the existing server instead of destroying it?

We could add a `reinstall` flag, but now that I'm starting to think about it, it seems like it makes much more sense to always reinstall the machine on update (when required, of course) instead of terminating it and taking a new one. At least I cannot come up with a use case were reinstalling wouldn't be a better choice.

@littleblackcloud what are your thoughts on this?

**Comment by littleblackcloud** [comment]
>it seems like it makes much more sense to always reinstall the machine on update (when required, of course) instead of terminating it and taking a new one

@zalmarge I agree with you that it makes sense to trigger a reinstall when the user_data changes. This is the approach that Latitude.sh have adopted in their [terraform provider](https://registry.terraform.io/providers/latitudesh/latitudesh/latest/docs/resources/server#user_data) and [implementation](https://github.com/latitudesh/terraform-provider-latitudesh/blob/main/latitudesh/resource_server.go#L17).

**Comment by littleblackcloud** [comment]
Just wanted to say thank you for the quick turn around!
The `allow_reinstall` option works great :D
