### ISSUE TITLE
Does not properly detect whether the server is running (seems like a failure to retrieve primary_ip)

### ISSUE THREAD

**Issue by Ivshti** [cherryservers/terraform-provider-cherryservers#6]
I'm experiencing the following behavior: deploying a server takes roughly 50m of waiting.

My theory is that the `waitForServer` method times out. I believe this for two reasons:
- that's it's timeout, as defined by 300*10 seconds: https://github.com/cherryservers/terraform-provider-cherryservers/blob/master/cherryservers/resource_cherryservers_server.go#L248
- my local version that I got from `terraform get` probably precedes this [error fix](https://github.com/cherryservers/terraform-provider-cherryservers/commit/3012f8e3a9155230980c62026093e56e9114b155), since when I, for example, try to deploy a server w/o a correct plan ID, it does not report an error and continues waiting

For some reason, even though the server is deployed (as I can see in the dashboard) and I can ssh to it, the terraform provider fails to retrieve it's IP. When I don't attempt to use `.primary_ip`, terraform shows "Apply complete!" after ~50m, but when I try to use it, terraform fails with:

```
1 error occurred:
	* cherryservers_server.deployer: Resource 'cherryservers_server.deployer' does not have attribute 'primary_ip' for variable 'cherryservers_server.deployer.primary_ip'
```

Again, after ~50m

**Comment by gthieleb** [comment]
Sorry to pick over the bones. Is this provider still alive?

**Comment by zalmarge** [comment]
> I'm experiencing the following behavior: deploying a server takes roughly 50m of waiting.
> 
> My theory is that the `waitForServer` method times out. I believe this for two reasons:
> 
> * that's it's timeout, as defined by 300*10 seconds: https://github.com/cherryservers/terraform-provider-cherryservers/blob/master/cherryservers/resource_cherryservers_server.go#L248
> * my local version that I got from `terraform get` probably precedes this [error fix](https://github.com/cherryservers/terraform-provider-cherryservers/commit/3012f8e3a9155230980c62026093e56e9114b155), since when I, for example, try to deploy a server w/o a correct plan ID, it does not report an error and continues waiting
> 
> For some reason, even though the server is deployed (as I can see in the dashboard) and I can ssh to it, the terraform provider fails to retrieve it's IP. When I don't attempt to use `.primary_ip`, terraform shows "Apply complete!" after ~50m, but when I try to use it, terraform fails with:
> 
> ```
> 1 error occurred:
> 	* cherryservers_server.deployer: Resource 'cherryservers_server.deployer' does not have attribute 'primary_ip' for variable 'cherryservers_server.deployer.primary_ip'
> ```
> 
> Again, after ~50m

I cannot seem to replicate the issue anymore, but well... Given the age of this issue and the many changes that have taken place since then, it doesn't come to me as a surprise.

Closing.
